#cloud-config

hostname: pgid-authority

package_update: false
package_upgrade: false

ssh_deletekeys: true
ssh_genkeytypes:
  - rsa
  - ecdsa
  - ed25519

runcmd:
  - [systemctl, daemon-reload]
  - [chmod, +x, /opt/spire-demo/authority/firstboot/authority-firstboot.sh]
  - [/opt/spire-demo/authority/firstboot/authority-firstboot.sh]
  - [mkdir, -p, /var/lib/spire-demo]
  - [python3, /opt/spire-demo/authority/build/generate-authority-manifest.py, --output, /var/lib/spire-demo/authority-manifest.json]
