#cloud-config

hostname: pgid-authority-build

package_update: true
package_upgrade: false

packages:
  - git
  - curl
  - ca-certificates

runcmd:
  - [git, clone, https://github.com/Arthurabriel/cloud-init-demo.git, /opt/spire-demo]
  - [git, -C, /opt/spire-demo, checkout, 89e597ddeb8d1ad2cd0fec23b8d8a3f9a89daa6e]
  - [chmod, +x, /opt/spire-demo/authority/build/bootstrap-authority-image.sh]
  - [/opt/spire-demo/authority/build/bootstrap-authority-image.sh, --no-start]
